name: Project testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - run: dotnet build ./tests/Application.UnitTests/MyHome.Common.UnitTests.csproj
      - run: dotnet test ./tests/Application.UnitTests/MyHome.Common.UnitTests.csproj
      - name: Test with dotnet
        run: dotnet test --logger trx --results-directory TestResults
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-results
          path: TestResults
        if: ${{ always() }}